Next web
Dflexcee/NEXT-WEB-PROJECT pull request #1
Opened 2019-11-20 00:21 UTC by Dflexcee

This is my Project: Next web html/css project
This was done alone by me followed by the instruction of the success student. This is due to the absence of my coding partner. i have been paired twice and none of them did not show up. So Willio sent me A mail to continue with HTML because currently no one to be paired me with again.

Nevertheless, my previous projects has been approved and i did it alone. But i was advice by last reviewer to add this go Ahead instruction in my PR.
Thanks for your understanding.

2019-11-20 06:14 UTC, suretrust requested changes
Hi @Dflexcee,

### Great work thus far, :raised_hands: however, there a still a lot of stuff to fix. Please see my comments on your code below.

- [ ] The medium screen needs to be fixed for all sections of the website `=> from navbar to footer`.

**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_ :tada:

2019-11-20 06:14 UTC, suretrust commented on index.html
> +    </div>
The navigation bar is missing the search icon on the right-hand side on a large screen. Please refer to the images below:
**Original**
![nav](https://user-images.githubusercontent.com/31304943/69212470-b1be6680-0b61-11ea-8b8c-d75acde026c6.png)
**Yours**
![nav2](https://user-images.githubusercontent.com/31304943/69212471-b1be6680-0b61-11ea-8a0c-31852cf96377.png)

`[Optional]` It may look better if you vertically align those home buttons on the lower navigation bar.

2019-11-20 06:14 UTC, suretrust commented on index.html
> +    </div>
**Medium screen**
The logo should be as tall as the navigation bar. Kindly refer to the images  below:
**Original**
![nav](https://user-images.githubusercontent.com/31304943/69212844-b1729b00-0b62-11ea-8137-26a2d77c5db0.png)

**Yours**
![nav](https://user-images.githubusercontent.com/31304943/69212729-6ce6ff80-0b62-11ea-8d07-97ac72afd4d4.png)

2019-11-20 06:14 UTC, suretrust commented on index.html
> +    </div>
**Small screen**
Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to search icon). Refer to the images below:

**Original**
![nav](https://user-images.githubusercontent.com/31304943/69212985-18904f80-0b63-11ea-9bbc-f1a7cd8f22b1.png)
**Yours**
![nav2](https://user-images.githubusercontent.com/31304943/69212988-18904f80-0b63-11ea-8a0b-eaa4ea115306.png)

2019-11-20 06:14 UTC, suretrust commented on main.css
> +
You only have a media query for the small screen, you need for the medium screen as well. The medium screen entirely looks nothing like the original page. Kindly fix.

**CSS styles should use media queries for 3 breakpoints** 
* small: max-width around 700
* medium: max-width around 1000
* large: mwidth over 1000

2019-11-22 00:01 UTC, Anna-Myzukina commented
#### Pull Request under the review by Anna Muzykina (TSE)

2019-11-22 00:47 UTC, Anna-Myzukina commented
Hi @Dflexcee, 
#### Wow, your project looks :+1:  Great job clap , I can see all the parts that are needed to decorate the page are in here.

### But there are some issues that are blocking me to declare this project as complete.

### Page structure

#### Navigation bar
- [ ] TWN logo should appear at the leftmost part in the medium version. On Large version, Navbar should be without TWN logo. Please try to fix it.

*** Ogiginal ***

![large](https://user-images.githubusercontent.com/26605804/69387415-6bd2e100-0cce-11ea-8df7-6643bc8df528.png)

*** Your version *** 

![large2](https://user-images.githubusercontent.com/26605804/69387472-8e64fa00-0cce-11ea-8010-d6fedc546756.png)

#### Top 3 articles section

- [ ] It contains TWN logo at the top left corner of the row ([link to page](https://thenextweb.com/))
*** On this part should be logo ***
![logo1](https://user-images.githubusercontent.com/26605804/69387689-485c6600-0ccf-11ea-9147-bb47baa52202.png)

*** Such logo *** 

![logo](https://user-images.githubusercontent.com/26605804/69387677-3c70a400-0ccf-11ea-801e-784f91485018.png)

####  Latest news section

###### Medium version changes

* [ ] It aligns 3 articles per row ([link to page](https://thenextweb.com/))

*** In original it lookes like this ***

![Screenshot from 2019-11-22 02-30-46](https://user-images.githubusercontent.com/26605804/69387966-20213700-0cd0-11ea-9479-bc4c5a8380fd.png)

*** In your version *** 
![Screenshot from 2019-11-22 02-32-26](https://user-images.githubusercontent.com/26605804/69388050-578fe380-0cd0-11ea-91b4-38e6c8963d6a.png)

###### Small version changes

* [ ] Each articles has a cover image on the left side and title on the right side of the row ([link to page](https://thenextweb.com/))

*** Small version should look like this ***

![Screenshot from 2019-11-22 02-33-56](https://user-images.githubusercontent.com/26605804/69388127-9de54280-0cd0-11ea-9f78-b1f1d74e0c1b.png)

*** In your project it still looks like this ***
![Screenshot from 2019-11-22 02-34-56](https://user-images.githubusercontent.com/26605804/69388164-bd7c6b00-0cd0-11ea-974b-928f3410b5d1.png)

##### Latest Funding section

###### Medium version changes

* [ ] It aligns 3 articles per row ([link to page](https://thenextweb.com/))

##### Categories (Apps, GERA, Tech, etc) section

###### Medium version changes

* [ ] It aligns 2 category boxes per row ([link to page](https://thenextweb.com/))

##### Latest deals section

###### Large version

###### Medium version changes

* [ ] It aligns 3 deals per row ([link to page](https://thenextweb.com/))

##### Footer

* [ ] It contains TNW logo with a copyright paragraph ([link to page](https://thenextweb.com/)). Please add TNW logo to your footer

*** As you can see logo in original version ***

![logofooter](https://user-images.githubusercontent.com/26605804/69388608-0f71c080-0cd2-11ea-8929-d3d16a823f63.png)


### Make changes and submit another code review request.


*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

2019-11-22 00:48 UTC, Anna-Myzukina requested changes
The project still needs changes

2019-11-26 09:20 UTC, fatymahmed commented
## Hello @Dflexcee,
I see that you have done a good job on making changes according to the previous TSE's review, but there's one more thing to fix 👏👏
- As you can see the requirement shown below is missing,

![Screenshot from 2019-11-26 12-05-51](https://user-images.githubusercontent.com/16196289/69615612-3e779180-1046-11ea-9fa6-e8445afd4dab.png)
 - Here is the original website navbar once you start scrolling, the logo can be seen .
![original](https://user-images.githubusercontent.com/16196289/69615744-78e12e80-1046-11ea-866d-a12513a50460.png)

- Here is your navbar when one scrolls, there's no logo
![current](https://user-images.githubusercontent.com/16196289/69615790-8eeeef00-1046-11ea-88f1-d3ca5eb7f99a.png)

2019-11-26 09:24 UTC, fatymahmed requested changes
## Make changes and submit another code review request.

If you have any questions, let me know on slack (fatima) and I will be happy to help you.

2019-11-26 14:05 UTC, Dflexcee commented
> 
> ## Make changes and submit another code review request.
> 
> If you have any questions, let me know on slack (fatima) and I will be happy to help you.

GOOD AFTERNOON,  I HAVE UNDERGO SERIES OF TSE WHO REVIEW MY CODE. PLEASE THE FUTURE YOU ARE ASKING IS DONE JAVASCRIPT. THAT SHOW ELEMENT ON SCROLL. I AM STILL IN HTMLS AND CSS. PLEASE HELP ME AND APPROVE MY WORK SO I CAN MOVE ON.  AS I MOVE ON I WILL LEAN MORE.

2019-11-26 14:06 UTC, Dflexcee commented
> 
> ## Hello @Dflexcee,
> 
> I see that you have done a good job on making changes according to the previous TSE's review, but there's one more thing to fix 👏👏
> 
>     * As you can see the requirement shown below is missing,
> 
> 
> ![Screenshot from 2019-11-26 12-05-51](https://user-images.githubusercontent.com/16196289/69615612-3e779180-1046-11ea-9fa6-e8445afd4dab.png)
> 
>     * Here is the original website navbar once you start scrolling, the logo can be seen .
>       ![original](https://user-images.githubusercontent.com/16196289/69615744-78e12e80-1046-11ea-866d-a12513a50460.png)
> 
>     * Here is your navbar when one scrolls, there's no logo
>       ![current](https://user-images.githubusercontent.com/16196289/69615790-8eeeef00-1046-11ea-88f1-d3ca5eb7f99a.png)
GOOD AFTERNOON,  I HAVE UNDERGO SERIES OF TSE WHO REVIEW MY CODE. PLEASE THE FUTURE YOU ARE ASKING IS DONE JAVASCRIPT. THAT SHOW ELEMENT ON SCROLL. I AM STILL IN HTMLS AND CSS. PLEASE HELP ME AND APPROVE MY WORK SO I CAN MOVE ON.  AS I MOVE ON I WILL LEAN MORE.

2019-11-27 00:02 UTC, fatymahmed commented
> > ## Make changes and submit another code review request.
> > If you have any questions, let me know on slack (fatima) and I will be happy to help you.
> 
> GOOD AFTERNOON, I HAVE UNDERGO SERIES OF TSE WHO REVIEW MY CODE. PLEASE THE FUTURE YOU ARE ASKING IS DONE JAVASCRIPT. THAT SHOW ELEMENT ON SCROLL. I AM STILL IN HTMLS AND CSS. PLEASE HELP ME AND APPROVE MY WORK SO I CAN MOVE ON. AS I MOVE ON I WILL LEAN MORE.

Hi @Dflexcee, I hope this was solved after I explained further on slack, otherwise please do reach out to me again on slack if you still have any problems

2019-11-27 11:55 UTC, fatymahmed approved these changes
## Hi @Dflexcee,
Great job on making the changes.
Congratulations on completing the project 👏👏👏, you can go ahead and merge.

## Status : Approved

2019-11-27 14:37 UTC, merged